// engine/game/factor-definitions.ts
import type { FactorDefinition, PreplacedElement, Surface } from '@/types/game';

// =============================================================================
// FACTOR DEFINITIONS (v2: Initiation + Amplification + Propagation)
// =============================================================================

export const FACTOR_DEFINITIONS: Record<string, FactorDefinition> = {
  FX: {
    id: 'FX',
    inactiveLabel: 'FX',
    activeLabel: 'FXa',
    category: 'zymogen',
    targetSurface: 'tf-cell',
    activationMessage: 'FXa generated on TF-cell surface (TF+VIIa catalyzes)',
    errorMessageWrongSlot: 'FX must be placed on TF-bearing cell where TF+VIIa can activate it.',
    prerequisites: [],
    thrombinContribution: 0,
    color: '#3B82F6', // blue
  },
  FIX: {
    id: 'FIX',
    inactiveLabel: 'FIX',
    activeLabel: 'FIXa',
    category: 'zymogen',
    targetSurface: 'tf-cell',
    activationMessage: 'FIXa generated on TF-cell (TF+VIIa catalyzes). Held in circulation.',
    errorMessageWrongSlot: 'FIX must be placed on TF-bearing cell where TF+VIIa can activate it.',
    prerequisites: [],
    thrombinContribution: 0,
    color: '#06B6D4', // cyan
  },
  FII: {
    id: 'FII',
    inactiveLabel: 'FII',
    activeLabel: 'Starter THR',
    category: 'zymogen',
    targetSurface: 'tf-cell',
    activationMessage: 'Starter thrombin produced → diffuses to platelet, activates PAR receptors',
    errorMessageWrongSlot: 'FII must be placed on TF-bearing cell where FXa + Va can generate thrombin.',
    prerequisites: ['FX'], // FXa must be present
    thrombinContribution: 30,
    color: '#EF4444', // red
  },
  FV: {
    id: 'FV',
    inactiveLabel: 'FV',
    activeLabel: 'FVa',
    category: 'procofactor',
    targetSurface: 'platelet',
    activationMessage: 'FVa activated on platelet surface (thrombin cleaves)',
    errorMessageWrongSlot: 'FV must be placed on activated platelet surface.',
    prerequisites: [], // only needs platelet unlocked (thrombin threshold)
    thrombinContribution: 0,
    color: '#8B5CF6', // purple
  },
  FVIII: {
    id: 'FVIII',
    inactiveLabel: 'FVIII+vWF',
    activeLabel: 'FVIIIa',
    category: 'procofactor',
    targetSurface: 'platelet',
    activationMessage: 'FVIIIa activated, dissociates from vWF (thrombin cleaves)',
    errorMessageWrongSlot: 'FVIII must be placed on activated platelet surface.',
    prerequisites: [], // only needs platelet unlocked
    thrombinContribution: 0,
    color: '#EC4899', // pink
  },
  // Activated FIXa - spawns in Propagation, docks into Tenase enzyme slot
  FIXa: {
    id: 'FIXa',
    inactiveLabel: 'FIXa',
    activeLabel: 'FIXa',
    category: 'enzyme',
    targetSurface: 'activated-platelet',
    activationMessage: 'FIXa docked into Tenase complex',
    errorMessageWrongSlot: 'FIXa docks into Tenase enzyme slot on activated platelet.',
    prerequisites: [],
    thrombinContribution: 0,
    color: '#06B6D4', // cyan (same as FIX)
  },

  // Special FXa spawned by Tenase complex (not in player palette)
  'FXa-tenase': {
    id: 'FXa-tenase',
    inactiveLabel: 'FXa',
    activeLabel: 'FXa',
    category: 'enzyme',
    targetSurface: 'activated-platelet',
    activationMessage: 'FXa (generated by Tenase on activated platelet)',
    errorMessageWrongSlot: 'This FXa docks into Prothrombinase.',
    prerequisites: [],
    thrombinContribution: 0,
    color: '#3B82F6',
  },

  // =============================================================================
  // STABILIZATION PHASE FACTORS
  // =============================================================================

  Fibrinogen: {
    id: 'Fibrinogen',
    inactiveLabel: 'Fibrinogen',
    activeLabel: 'Fibrin',
    category: 'zymogen',
    targetSurface: 'clot-zone',
    activationMessage: 'Fibrinogen cleaved to Fibrin monomer (thrombin catalyzes)',
    errorMessageWrongSlot: 'Fibrinogen must be placed in Clot Zone where thrombin can cleave it.',
    prerequisites: [], // needs stabilization phase to be active (phase gating)
    thrombinContribution: 0,
    color: '#F97316', // orange
  },
  FXIII: {
    id: 'FXIII',
    inactiveLabel: 'FXIII',
    activeLabel: 'FXIIIa',
    category: 'zymogen',
    targetSurface: 'clot-zone',
    activationMessage: 'FXIIIa activated, cross-links fibrin strands (thrombin catalyzes)',
    errorMessageWrongSlot: 'FXIII must be placed in Clot Zone where thrombin can activate it.',
    prerequisites: [], // needs stabilization phase to be active (phase gating)
    thrombinContribution: 0,
    color: '#FBBF24', // amber/gold
  },
} as const;

// =============================================================================
// PRE-PLACED ELEMENTS (always visible on TF-cell)
// =============================================================================

export const PREPLACED_ELEMENTS: PreplacedElement[] = [
  {
    id: 'tf-viia',
    label: 'TF+VIIa',
    tooltip: 'Tissue Factor + Factor VIIa complex. Initiates coagulation.',
    surface: 'tf-cell',
    isDim: false,
  },
  {
    id: 'va-trace',
    label: 'Va (trace)',
    tooltip: 'Trace cofactor activity enables starter thrombin generation.',
    surface: 'tf-cell',
    isDim: true,
  },
];

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

export function getFactorDefinition(factorId: string): FactorDefinition | null {
  return FACTOR_DEFINITIONS[factorId] ?? null;
}

export function getAllFactorIds(): string[] {
  return Object.keys(FACTOR_DEFINITIONS);
}

export function getFactorsByTargetSurface(surface: Surface): FactorDefinition[] {
  return Object.values(FACTOR_DEFINITIONS).filter((f) => f.targetSurface === surface);
}
