import { Factor } from '@/types';

export const CANVAS_WIDTH = 800;
export const CANVAS_HEIGHT = 600;

export function createInitialFactors(): Record<string, Factor> {
  return {
    // Calea Intrinsecă (stânga)
    F12: {
      id: 'F12',
      name: 'Factor XII (Hageman)',
      shortName: 'XII',
      position: { x: 150, y: 80 },
      activity: 1.0,
      baseActivity: 1.0,
      vitKDependent: false,
      parents: [],
      children: ['F11'],
      pathway: 'intrinsic',
    },
    F11: {
      id: 'F11',
      name: 'Factor XI',
      shortName: 'XI',
      position: { x: 150, y: 160 },
      activity: 1.0,
      baseActivity: 1.0,
      vitKDependent: false,
      parents: ['F12'],
      children: ['F9'],
      pathway: 'intrinsic',
    },
    F9: {
      id: 'F9',
      name: 'Factor IX (Christmas)',
      shortName: 'IX',
      position: { x: 150, y: 240 },
      activity: 1.0,
      baseActivity: 1.0,
      vitKDependent: true,
      parents: ['F11'],
      children: ['F8'],
      pathway: 'intrinsic',
    },
    F8: {
      id: 'F8',
      name: 'Factor VIII',
      shortName: 'VIII',
      position: { x: 200, y: 320 },
      activity: 1.0,
      baseActivity: 1.0,
      vitKDependent: false,
      parents: ['F9', 'vWF'],
      children: ['F10'],
      pathway: 'intrinsic',
    },

    // Calea Extrinsecă (dreapta)
    TF: {
      id: 'TF',
      name: 'Tissue Factor',
      shortName: 'TF',
      position: { x: 550, y: 80 },
      activity: 1.0,
      baseActivity: 1.0,
      vitKDependent: false,
      parents: [],
      children: ['F7'],
      pathway: 'extrinsic',
    },
    F7: {
      id: 'F7',
      name: 'Factor VII',
      shortName: 'VII',
      position: { x: 550, y: 160 },
      activity: 1.0,
      baseActivity: 1.0,
      vitKDependent: true,
      parents: ['TF'],
      children: ['F10'],
      pathway: 'extrinsic',
    },

    // Calea Comună (centru-jos)
    F10: {
      id: 'F10',
      name: 'Factor X (Stuart-Prower)',
      shortName: 'X',
      position: { x: 350, y: 340 },
      activity: 1.0,
      baseActivity: 1.0,
      vitKDependent: true,
      parents: ['F8', 'F7'],
      children: ['F5'],
      pathway: 'common',
    },
    F5: {
      id: 'F5',
      name: 'Factor V (Proaccelerin)',
      shortName: 'V',
      position: { x: 350, y: 400 },
      activity: 1.0,
      baseActivity: 1.0,
      vitKDependent: false,
      parents: ['F10'],
      children: ['F2'],
      pathway: 'common',
    },
    F2: {
      id: 'F2',
      name: 'Factor II (Protrombină)',
      shortName: 'II',
      position: { x: 350, y: 460 },
      activity: 1.0,
      baseActivity: 1.0,
      vitKDependent: true,
      parents: ['F5'],
      children: ['FBG'],
      pathway: 'common',
    },
    FBG: {
      id: 'FBG',
      name: 'Fibrinogen → Fibrină',
      shortName: 'Fbg',
      position: { x: 350, y: 530 },
      activity: 1.0,
      baseActivity: 1.0,
      vitKDependent: false,
      parents: ['F2'],
      children: ['F13'],
      pathway: 'common',
    },
    F13: {
      id: 'F13',
      name: 'Factor XIII (Stabilizare)',
      shortName: 'XIII',
      position: { x: 450, y: 530 },
      activity: 1.0,
      baseActivity: 1.0,
      vitKDependent: false,
      parents: ['FBG'],
      children: [],
      pathway: 'common',
    },

    // Elemente Celulare (mod clinic)
    vWF: {
      id: 'vWF',
      name: 'von Willebrand Factor',
      shortName: 'vWF',
      position: { x: 80, y: 320 },
      activity: 1.0,
      baseActivity: 1.0,
      vitKDependent: false,
      parents: [],
      children: ['F8', 'PLT'],
      pathway: 'platelet',
    },
    PLT: {
      id: 'PLT',
      name: 'Trombocite',
      shortName: 'Plt',
      position: { x: 80, y: 400 },
      activity: 1.0,
      baseActivity: 1.0,
      vitKDependent: false,
      parents: ['vWF'],
      children: [],
      pathway: 'platelet',
    },

    // Inhibitori (mod clinic)
    AT: {
      id: 'AT',
      name: 'Antitrombina III',
      shortName: 'AT',
      position: { x: 620, y: 400 },
      activity: 1.0,
      baseActivity: 1.0,
      vitKDependent: false,
      parents: [],
      children: [],
      pathway: 'fibrinolysis',
    },
    PC: {
      id: 'PC',
      name: 'Proteina C',
      shortName: 'PC',
      position: { x: 620, y: 460 },
      activity: 1.0,
      baseActivity: 1.0,
      vitKDependent: true,
      parents: [],
      children: [],
      pathway: 'fibrinolysis',
    },
    PS: {
      id: 'PS',
      name: 'Proteina S',
      shortName: 'PS',
      position: { x: 700, y: 460 },
      activity: 1.0,
      baseActivity: 1.0,
      vitKDependent: true,
      parents: [],
      children: [],
      pathway: 'fibrinolysis',
    },
  };
}

export const BASIC_MODE_FACTORS = ['F12', 'F11', 'F9', 'F8', 'TF', 'F7', 'F10', 'F5', 'F2', 'FBG', 'F13'];
export const CLINICAL_MODE_FACTORS = [...BASIC_MODE_FACTORS, 'vWF', 'PLT', 'AT', 'PC', 'PS'];
